### ISSUE TITLE
Missing devcies

### ISSUE THREAD

**Issue by biggy5252** [AdyRock/com.lightwaverf.smartseries#1]
Hello, Thank you for this app, please add these devices to the supported list of devices in your next upgrade.

[
  {
    "device": {
      "productCode": "LW260",
      "device": "socket",
      "desc": "One Gang Socket",
      "type": "lwrfOneWay_v1",
      "cat": "Power",
      "gen": 1,
      "switch": "Yes",
      "protection": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW260",
      "device": "socket",
      "desc": "One Gang Socket",
      "type": "lwrfOneWay_v1",
      "cat": "Power",
      "gen": 1,
      "switch": "Yes",
      "protection": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW934",
      "device": "electricSwitch",
      "desc": "Electric Switch",
      "type": "lwrfTwoWay_v1",
      "cat": "Heating",
      "gen": 1,
      "temperature": "Yes",
      "targetTemperature": "Yes",
      "valveLevel": "Yes",
      "heatState": "Yes",
      "rssi": "Yes"
    }
  },
  {
    "device": {
      "productCode": "L2",
      "device": "LinkPlus",
      "desc": "Central Hub",
      "type": "lwrfTwoWay_v2",
      "cat": "Hub",
      "gen": 2,
      "currentTime": "Yes",
      "buttonPress": "Yes",
      "time": "Yes",
      "date": "Yes",
      "monthArray": "Yes",
      "weekdayArray": "Yes",
      "timeZone": "Yes",
      "locationLongitude": "Yes",
      "locationLatitude": "Yes",
      "duskTime": "Yes",
      "dawnTime": "Yes",
      "rgbColor": "Yes",
      "day": "Yes",
      "month": "Yes",
      "year": "Yes",
      "weekday": "Yes"
    }
  }
]

**Comment by AdyRock** [comment]
OK I have added the LW260 to the 1.1.1 beta that I will submit soon.
The LW934 will take a bit more work as it is a new class and I don't have any of those to test with but I will look into it as soon as I get some spare time.

**Comment by biggy5252** [comment]
Thank you very much. 

Is there a way we can make the LW934 just work as a switch for now, ON/OFF state only. I is a boiler switch, with thermostat features, however my aim is for now to use it as a high power ON/OFF switch and not use any other advanced features. 

Take your time, no problem, and thank you once again.

**Comment by AdyRock** [comment]
The beta 1.1.1 has now been published with support for the LW260. As I don't have one it is untested so let me know if there are any problems.
 
I will see what I can do with the LW934 but I guess the switch operates when the current temperature is below the set temperature so I'm not sue if it can be switched off and on directly. I will try to get some information from LW about it.

**Comment by biggy5252** [comment]
Thank you, 

the LW934 can be switched on and off directly as well using the app. Incase you would like access to my LW account which has this switch , I can share it with you, you can login the LW app on your phone, and their webUI to check its features, if that will help.

**Comment by thackrad** [comment]
Thanks for the app Ady. Addition of LW934, even as a switch, would be much appreciated! :)

**Comment by AdyRock** [comment]
The LW934 looks interesting so I have ordered one then I can integrate and test it.

**Comment by AdyRock** [comment]
I now have the LW934 and I have made some progress. I'm trying to get my head around the on / off button as it seems to toggle between standby (off) and auto (temperature controlled) modes. However, it also seems to set the target temperature to 40 at times but never drops it back down again. The LW app behaves differently as it only toggles between standby and auto and never adapts the target temperature.
I am guessing that to use the button as a relay on / off the target temperature will need to be set so heat demand is always required. E.g. set target temperature to 40 like the physical button does. Then the stand by mode will switch it off and the auto mode will switch it on.
Also I can't see any way to get a notification when the Boost button is press, except for the valveValue being set if it was off.
The valveValue just toggles between 0 and 100 when the relay switches off and on.

**Comment by biggy5252** [comment]
Hello Ady, 

This is certainly a weird switch. They call it an electric switch, but functions as a boiler switch with thermostat setting. 

What I have noticed is that when the switch is off/standby and the internet temperature probe reaches below 25 degrees, it automatically powers on the switch. 

I hope you have some luck in just letting it be ON and OFF onto Homey.

**Comment by AdyRock** [comment]
I think to use it as a switch you should be able to set the temperature to max (40) and then use the on / off button or tile to switch it.
I will submit a new beta so you can try it and let me know if it works the way you want.

**Comment by AdyRock** [comment]
Beta has been posted. Let me know if there any issues.

**Comment by thackrad** [comment]
Everything looks good so far Ady, great stuff, thank you!

**Comment by AdyRock** [comment]
Excellent. You are welcome.

**Comment by biggy5252** [comment]
Excellent update Ady, I tested the final version of the app, and it seems all devices are working fine. 

I tried to push the LW934 to HomeKit via HomeyKit, and because it went as a thermostat, it only sent temperature and modes and not ON>OFF feature. So basically work around is the create a VD linking to ON/OFF mode of the LW934 and push the VD to HomeKit. So my problem is completely solved.

Thank you very much for the assistance.

**Comment by AdyRock** [comment]
Thank you for the feedback. I'm glad you found a suitable work around for HomeKit.

**Comment by thackrad** [comment]
Hi Ady, I have a number of LW107 PIR motion sensors that I'd really like to
use with the LW Smart Series dimmers I have. Doing that via Homey is one
way that may work. Any chance you include this device in your app please?
Thanks
David

**Comment by AdyRock** [comment]
Hi.
Do the LW107 appear in the LW smart series app?
If they do then they should show up in my app under the unsupported device list. If they are there can you send me a copy of the list. 

If they can't be added to the LW app then I can't support them either. 

Maybe Athom could add support in their app if that's the case.

**Comment by thackrad** [comment]
Thanks for the response Ady. No, they don’t appear in the app. Thanks anyway.

 

Cheers

David

**Comment by AdyRock** [comment]
Hi David,

Just a long shot, but have you tried the Athom LW app and checked if you can add the LW107 as a LW100?
I had a play this evening and found that I can add my LW201 under that device and the On / Off buttons come in as channel D Button 1 On / Off. So try adding the LW100 and when it says press a button try activating the sensor. If it comes up with a tick then it added it. Then, on the test screen, activate the sensor again and it will move the channel switch and highlight the button that it thinks has been pressed.

Best regards,
Adrian.

**Comment by thackrad** [comment]
Thanks Ady, I'll try that

**Comment by thackrad** [comment]
No, afraid that doesn't work Ady. Thanks anyway.

David M Thackray

**Comment by AdyRock** [comment]
It was a long shot so not surprised but it was worth a try. 
Hopefully Athom can add it in.
