### ISSUE TITLE
Missing devices

### ISSUE THREAD

**Issue by thackrad** [AdyRock/com.lightwaverf.smartseries#2]
Hi, thanks for the app. Here are my missing items, appreciate anything you can add. Thanks again. D

[
  {
    "device": {
      "productCode": "L2",
      "device": "LinkPlus",
      "desc": "Central Hub",
      "type": "lwrfTwoWay_v2",
      "cat": "Hub",
      "gen": 2,
      "currentTime": "Yes",
      "buttonPress": "Yes",
      "time": "Yes",
      "date": "Yes",
      "monthArray": "Yes",
      "weekdayArray": "Yes",
      "timeZone": "Yes",
      "locationLongitude": "Yes",
      "locationLatitude": "Yes",
      "duskTime": "Yes",
      "dawnTime": "Yes",
      "rgbColor": "Yes",
      "day": "Yes",
      "month": "Yes",
      "year": "Yes",
      "weekday": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW400",
      "device": "light",
      "desc": "One Gang Dimmer",
      "type": "lwrfOneWay_v1",
      "cat": "Lighting",
      "gen": 1,
      "switch": "Yes",
      "protection": "Yes",
      "dimLevel": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW400",
      "device": "light",
      "desc": "One Gang Dimmer",
      "type": "lwrfOneWay_v1",
      "cat": "Lighting",
      "gen": 1,
      "switch": "Yes",
      "protection": "Yes",
      "dimLevel": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW400",
      "device": "light",
      "desc": "One Gang Dimmer",
      "type": "lwrfOneWay_v1",
      "cat": "Lighting",
      "gen": 1,
      "switch": "Yes",
      "protection": "Yes",
      "dimLevel": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW921",
      "device": "thermostat",
      "desc": "Thermostat",
      "type": "lwrfTwoWay_v1",
      "cat": "Heating",
      "gen": 1,
      "temperature": "Yes",
      "targetTemperature": "Yes",
      "valveLevel": "Yes",
      "heatState": "Yes",
      "batteryLevel": "Yes",
      "rssi": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW934",
      "device": "electricSwitch",
      "desc": "Electric Switch",
      "type": "lwrfTwoWay_v1",
      "cat": "Heating",
      "gen": 1,
      "temperature": "Yes",
      "targetTemperature": "Yes",
      "valveLevel": "Yes",
      "heatState": "Yes",
      "rssi": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW922",
      "device": "valve",
      "desc": "TRV",
      "type": "lwrfTwoWay_v1",
      "cat": "Heating",
      "gen": 1,
      "temperature": "Yes",
      "targetTemperature": "Yes",
      "valveLevel": "Yes",
      "heatState": "Yes",
      "batteryLevel": "Yes",
      "rssi": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW831",
      "device": "light",
      "desc": "In-line Dimmer",
      "type": "lwrfOneWay_v1",
      "cat": "Lighting",
      "gen": 1,
      "switch": "Yes",
      "protection": "Yes",
      "dimLevel": "Yes"
    }
  },
  {
    "device": {
      "productCode": "LW400",
      "device": "light",
      "desc": "One Gang Dimmer",
      "type": "lwrfOneWay_v1",
      "cat": "Lighting",
      "gen": 1,
      "switch": "Yes",
      "protection": "Yes",
      "dimLevel": "Yes"
    }
  }
]

**Comment by AdyRock** [comment]
The dimmers should be no problem so will add those in the next update for sure.
I am working on the LW934, having now got one. That is taking shape but trying to work out the best way to handle the button. It seems the real button press behaves differently to the LW App button press so deciding which method to adopt.
Once the 934 is sorted the 921 and 922 should drop into place with the same driver. So fingers crossed, the next update should handle all of your devices.

**Comment by thackrad** [comment]
Great news, thanks Ady!

**Comment by AdyRock** [comment]
One thing has dawned on me; the gen 1 dimmers might not update the app when operated at the device as they only have one-way communications. Therefore the triggers won't work in flows. Nothing I can do about that though.

**Comment by thackrad** [comment]
Yes, understood, no worries. Thanks.

**Comment by thackrad** [comment]
WRT the thermostat (LW921) and electric switch (LW934), i don't use the switch independently of the thermostat, so if the thermostat was configured and available then that would do it for me. Thanks.

**Comment by AdyRock** [comment]
Yep, they should both have access to view and set the target temperature. I have only tested the LW934 as that is all I have but it looks like the others have the same interface.
I have also added the switch contact as a general alarm so flows can be triggers when the relay changes state.

**Comment by thackrad** [comment]
Great, nice one, thanks. Will there be a new beta published with these additions, or is there another way of getting it?

**Comment by AdyRock** [comment]
I submitted a new beta this morning so waiting for Athom to review and publish it. They normally take about a day but it can be less or it could be a week.
You could grab the code from the repository and load it via the Homey CLI if you want. The instructions are here [Getting Started](https://apps.developer.athom.com/tutorial-Getting%20Started.html).

**Comment by thackrad** [comment]
Thanks Ady

**Comment by AdyRock** [comment]
Beta has been posted. Let me know if there are any issues
