### ISSUE TITLE
LW934

### ISSUE THREAD

**Issue by biggy5252** [AdyRock/com.lightwaverf.smartseries#3]
Hello Adrian, 

I have been playing around with the LW934 feature you added on the app, thank you for that. I have come across a problem I am noticing, whenever I power on the LW934 either physically or via its own lightwave app, Homey does not report it to be powered on. This way there is no way of finding out if someone has physically turned on the switch or not. Is that something that could be fixed?

**Comment by AdyRock** [comment]
Hi,

The LW934 should be reporting the changes and I pretty sure I did test that. I meant to try it yesterday evening when I got home from work but I'm having a new kitchen extension so I was side tracked by that. As I don't currently use it I have to connect it back up again.

LW are having issues with the Webhooks at the moment and I have found various other LW devices that have stopped working and then started again so maybe it is a temporary problem. You could try to enable the polling mode to see if that helps for now.

I have contacted LW support along with other dev's and they have said they are making changes that could break the webhooks.

Let me know if the problem persists.

**Comment by AdyRock** [comment]
I presume this was just the LW glitch so I'm closing the issue but feel free to get back to me if the problem still exists.
