### ISSUE TITLE
Loss of two way communication of device status on sockets

### ISSUE THREAD

**Issue by bellringer2** [AdyRock/com.lightwaverf.smartseries#8]
When I add a device I choose socket and the app correctly offers me all the sockets that I had not previously added to homey. I choose the ones I want and they add correctly. The on/off status of these newly added devices is correctly reflected on homey no matter whether the it is changed from the lightwave app, from the lightwave physical switch or from the homey app.

The problem is that adding these new sockets breaks the synchronisation of status (on/off and power usage and probably more) for any previously added sockets. So changing the status on lightwave via app or switch or turning kettle on (in case of power usage) does not reflect in the homey app or in the case of power usage cause the start of a flow.

It is worth noting that changing the on/ off status of the device on homey does change it on lightwave so the link is not totally gone but homey is not reflecting changes made in lightwave.

My workaround is very annoying in that I have to delete all sockets and then add all again at the same time and then go and fix all my broken flows.

**Desktop (please complete the following information):**
 - OS: iOS

**Comment by AdyRock** [comment]
What version of the app are you using?

**Comment by bellringer2** [comment]
Your app 2.0.5 sorry should have included this

**Comment by AdyRock** [comment]
No problem. Could you try the test version. That has a rate limiter to ensure it doesn't make too many calls per second as LightWave starts to block things. 
You can install it from the app store by adding test to the end of the app URL.

**Comment by bellringer2** [comment]
Adrian

Thanks for your very prompt response. 

I will try the test version as you suggest but probably not until next weekend. 

I have to leave a working house for my partner (otherwise I will get a lot of grief) as I am away during the week. 

If the test version does the same then I’ll have to delete everything, add it again, fix the flows and test all is well.

I’ll get back to you as soon as possible. 

Regards

Peter

**Comment by bellringer2** [comment]
Adrian,

 

Sorry I still didn’t get opportunity to test this. I see the latest version has now downloaded to my Homey. Can I assume that this includes the test version you mentioned?

 

On a different matter. I really like and get great value from your code and would like to thank you with a small monetary contribution. How can I go about this? Please let know.

 

Regards

Peter

**Comment by AdyRock** [comment]
The new version does have the rate limit, but be aware that LightWave had an issue that broke all calls to the Webhook features on Saturday, 
and I haven't checked back to see if it is fixed. 
I did report it but had no reply yet.

**Comment by bellringer2** [comment]
Thanks Adrian,

You seem to have missed my second question which was how I can give a small monetary thank you for your excellent code.

Please let me know 
Regards
Peter

**Comment by AdyRock** [comment]
That's very kind, thank you. 
At the bottom of the app page in the store is a donate link that goes through PayPal.

**Comment by AdyRock** [comment]
Thank you for the generous gift. I really appreciate it.
